### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by mroglic** [wouterverweirder/kinect2#17]
I am not quite sure how to install, I unpacked zip to kinect2 folder on desktop and ran: npm install kinect2 but I got these errors:

C:\Users\mr\Desktop>npm install kinect2
\
> kinect2@0.0.31 install C:\Users\mr\Desktop\node_modules\kinect2
> node tools/install.js

C:\Users\mr\Desktop\node_modules\kinect2>if not defined npm_config_node_gyp (nod
e "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules
\node-gyp\bin\node-gyp.js" configure build )  else (node  configure build )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\mr\Desktop\node_modules\kinect2
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
kinect2@0.0.31 node_modules\kinect2
└── nan@2.0.8

**Comment by wouterverweirder** [comment]
As stated by the error message: you will need to install Python. More info on the github page of node-gyp: https://github.com/nodejs/node-gyp
