### ISSUE TITLE
socket.io ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by mroglic** [wouterverweirder/kinect2#19]
When I run any example and go to localhost:8000 a get a blank screen and this error in console:

GET http://localhost/socket.io/?EIO=3&transport=polling&t=1441152584189-0 net::ERR_CONNECTION_REFUSED

I assume that socket.io path could be wrong. Here is the structure of my folders:

C:\Users\mr\Desktop\node_modules
express
kinect2
socket.io

And then I run it in this folder C:\Users\mr\Desktop\node_modules\kinect2\examples\color-feed-browser>node index.js
Server listening on port 8000
Point your browser to http://localhost:8000

**Comment by wouterverweirder** [comment]
This might be windows firewall preventing socket setup. Do basic socket.io applications work? Have you tried other ports (instead of 8000)?

**Comment by mroglic** [comment]
It's working now, the problem was that I didn't install express and socket.io correctrly. Thanks!
