### ISSUE TITLE
No bodies logged

### ISSUE THREAD

**Issue by David-dp-** [wouterverweirder/kinect2#2]
This is what I tried:
1. Verified hardware connections by starting Kinect Studio and seeing myself wave to camera
2. While KS still connected, ran the sample app of this project. Saw only: 

 >node kinect2.node.js
 Kinect Opened
 [Kinect2] Created NodeKinect Instance
 [Kinect2] Open
 [Kinect2] OpenBodyReader
 Kinect Closed

3. Disconnected KS, then ran the sample app again. Output is same.

I didn't see any previous prior Issue, and there's no Wiki, so I suspect there's an undocumented step I missed. Please advise.

**Comment by David-dp-** [comment]
Can you suggest a way I can verify that the following does what it should?

  this.edge.openBodyReader = edge.func(_.assign({ methodName: 'OpenBodyReader' }, dllProperties));

I used VS Studio Express to look at what the dll exposes, and I couldn't find any 'OpenBodyReader'. I'd expect this module to use BodyFrameReader instead (which is what the Kinect Studio C# example uses, IIRC).

**Comment by wouterverweirder** [comment]
The basicexample only runs for 5 seconds. If you don't stand in front of the sensor, you won't see any additional output.

A more visual example is the skeletons-browser:
- npm install the dependencies inside that directory
- run with node: node index.js
- navigate to http://localhost:8000 with chrome. Skeletons of users in front of the sensor will be shown in the browser.

**Comment by David-dp-** [comment]
After doing this...

C:\Users\david\node_modules\kinect2\examples\skeletons-browser>node index.js
Server listening on port 8000
Point your browser to http://localhost:8000
[Kinect2] Created NodeKinect Instance
[Kinect2] Open
[Kinect2] OpenBodyReader

...I point Chrome v39 (running on same host) to http://localhost:8000/ The sensor's white and red lights come on, but the Chrome view remains blank white. Page source shows complete-looking markup, but I don't see a way to probe what's (not) happening via Dev Tools.

**Comment by wouterverweirder** [comment]
This error would indicate that lodash (dependency of my library) isn't working. Can you find the lodash directory inside the npm_modules directory? (normally within node_modules/kinect2/node_modules)

**Comment by David-dp-** [comment]
Here's the results of my unsuccessful investigation, formatted so it would be easy for you to copy/paste any part of it into your docs if you wanted...

1. Download and install node. For Win8.1 Pro 64bit use http://nodejs.org/dist/v0.10.29/x64/node-v0.10.29-x64.msi because otherwise you get ENOENT errors when npm tries to create folders even if you're using an admin cmd.

2. Ctrl+Q and enter "node.js command prompt". There seems no need to run as admin.

3. 'cd' to the folder where your project will be developed.

4. If you want to ensure that this installation of the kinect2 and its supporting modules (i.e., edge and lodash) don't conflict with versions that your other node projects might depend on, then make sure you don't have a C:\Users\[yourUserId]\node_modules\ folderpath.

5. Enter "npm install kinect2". Verify that cmd shows:

   Success: platform check for edge.js: node.js x64 v0.10.29
   kinect2@0.0.8 node_modules\kinect2
   ├── lodash@2.4.1
   └── edge@0.9.3 (edge-cs@0.2.7)

If the folderpath isn't exactly "node_modules\kinect2" like above, then it was installed on whatever folderpath is indicated and the following steps probably won't work for you.

6. Verify it works by trying the skeleton-browser example:

   Make sure your Kinect is fully connected to power and to a USB3 port on your PC
   cd node_modules\kinect2\examples\skeleton-browser\
   npm install
   node index.js
   Point your browser to localhost:8000
   Make sure your Kinect has an unoccluded view of someone and ask them to wave. The browser page should show red circles on most joints as they move.

  =========PROBLEM> The page remains blank for me.

7. Troubleshooting
7.1. Are you sure your Kinect is properly connected to power and PC? White and red lights are visible from its front when it's recording.
7.2. Right-click in the page and select "view source". Does it match the contents of public\index.html under the skeleton-browser folderpath?
7.3. Edit index.js by placing
       console.log('test bodies: '+ bodies +' type: '+ typeof(bodies));
     in the kinect.on callback, then repeat step 6 above.

  =========PROBLEM> I see "test bodies:  type: object" printed about once a second. Why is the object empty?

7.3. In cmd with skeleton-browser as the working dir, run node and paste each statement from index.js.

  =========PROBLEM> When I enter "var kinect = new Kinect2()", I get
                     TypeError: Cannot call method 'assign' of undefined at new Kinect2 (C:\Users\[...]\node_modules\kinect2\kinect2.js:16:33)
                    Here, 'assign' is a method of '_', which should have been defined when 'kinect2' was require'd because it in turn require's lodash.
                    I verified that starting from skeleton-browser, the lodash folder at ..\..\node_modules\lodash seems to have all its proper contents.

END

**Comment by David-dp-** [comment]
This seems to indicate something's wrong with skeleton-tracking in my Kinect binaries...

Ctrl+Q and enter "sdk browser v2.0 (kinect for windows)". Install and run "Body Basics-WPF". It should show a skeleton corresponding to the person moving in front of the sensor.

  =========PROBLEM> It appears blank black for me, but the Color and Depth demos work fine.

**Comment by David-dp-** [comment]
I solved my problem by changing the position of the sensor and the test person -- instead of having the sensor on a coffee table facing me a meter away while I sat with my laptop in my lap, I put the sensor at the edge of a table and stood 2-3 meters in front of it, while the laptop is angled so I can see the BodyBasics WPF display.
