### ISSUE TITLE
send 12bit depth data instead of 8

### ISSUE THREAD

**Issue by omaksi** [wouterverweirder/kinect2#23]
Would it be possible to send full 12bit of depth data instead of 8bit?

**Comment by wouterverweirder** [comment]
Hi @omaksi  - the raw depth data is available at it's native precision. Check https://github.com/wouterverweirder/kinect2/blob/master/examples/point-cloud-electron/index.html for an example (electron).

**Comment by omaksi** [comment]
Hi @wouterverweirder , thanks. 
I was missing the bitshift join needed for the raw data. It now works in native precision. :+1:
