### ISSUE TITLE
Help Request on Setting Up

### ISSUE THREAD

**Issue by mysunnytime** [wouterverweirder/kinect2#25]
Hi, 

Thanks so much for building this! I really hope I can use your lib to build my app! But I met some problems in the electron part when trying.

I have installed the Kinect2 SDK, installed the nodejs and used npm to installed the kinect2. Then I'm stuck by the electron part. To be honest I'm a novice of nodejs. So The tutorial says "**build this module for electron usage**" but I don't get that how to build the module. So I tried:

1. the link embedded in the text (https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md) I followed the method it mentions and run 

"npm install --save-dev electron-rebuild .\node_modules\.bin\electron-rebuild.cmd"

but ERRs occurred:
![image](https://cloud.githubusercontent.com/assets/5469750/13626092/4b187712-e573-11e5-85eb-94527a74925a.png)

2. Then I searched some electron tutorial and found this link http://tutorialzine.com/2015/12/creating-your-first-desktop-app-with-html-js-and-electron/. It tells me to run "npm install" first and "npm start" then, to build a module. So I tried that in your code. Then a node_modules appears after "npm install", but ERRs occur when "npm start":

![image](https://cloud.githubusercontent.com/assets/5469750/13626184/80cee0fc-e574-11e5-814b-42a9482f4ee4.png)

3. After all these I also tried to run your next command: "node tools\electronbuild.js --target=0.30.2 --arch=x64" - then a lot of ERRs:

![image](https://cloud.githubusercontent.com/assets/5469750/13626279/521a3d46-e575-11e5-8c32-e2b7e1a10e27.png)

Could you please tell me what should I do to set up your library and start any example? Thanks so much for that.

**Comment by wouterverweirder** [comment]
Hi, you were almost there: it looks like you're missing python on your system, which is needed to build the module from source.

Make sure to install Python 2.7.x (3.x is not supported) and retry the last command :-)
