### ISSUE TITLE
Error electron example

### ISSUE THREAD

**Issue by Loyth** [wouterverweirder/kinect2#34]
Hello everybody ! I executed these instructions
`npm install --save-dev electron-rebuild`
`.\node_modules\.bin\electron-rebuild.cmd`
`node tools\electronbuild.js --target=0.30.2 --arch=x64`

All done, any errors !

But after launched this instruction in the example 
`electron .`

The electron app has launched but Kinect didn't start.
When I go to the Developer Tools, this error appears in the console
`Uncaught Error: The specified procedure could not be found.
\\?\C:\Users\Thomas\Desktop\Stage Thomas\Electron\kinect2\build\Release\kinect2.node`

Do you have a solution ?
Thanks.

**Comment by wouterverweirder** [comment]
Looks like it didn't compile the electron version. Make sure to compile a version of this module for electron usage:

1. delete the build directory inside of this project
2. open a command line, and cd to the root of this project
3. execute `node tools\electronbuild.js --target=0.30.2 --arch=x64` (make sure that the target matches your electron version).

This should create the build directory with a compiled version for electron usage.
