### ISSUE TITLE
depth of joint

### ISSUE THREAD

**Issue by amejias101** [wouterverweirder/kinect2#35]
Is there a way to get depth of a joint? Right now I'm using the `bodyFrame` to get the X/Y coordinates of joints, but I'm not sure how to go about getting depth, since I'm not sure what each frame maps out to in the official Kinect documentation. Also, thank you so much for your work!

**Comment by wouterverweirder** [comment]
You can get the depth information in the camera-properties of each joint, e.g.:

```
bodies[i].joints[Kinect2.JointType.spineMid].cameraZ
```
