### ISSUE TITLE
How I can use aduio

### ISSUE THREAD

**Issue by jeefyang** [wouterverweirder/kinect2#36]
hello,thanks for your demo,it so power. I can create  a very beatiful demo.But I can not use aduio,you say Not Implemented Yet~~ I really want to use aduio to change my demo!!can you tell me how i can 
use aduio.whatever,thanks for your demo!!!

**Comment by wouterverweirder** [comment]
Hi - I'm not planning on adding new features at this moment, only keeping it up to date with new nodejs releases. Audio is one of the harder things, as it'll probably involve working with creating / passing streams from C++ to nodejs.

**Comment by jeefyang** [comment]
oh,that sound like terrible,but thanks for your answer~~
