### ISSUE TITLE
Detect when hand is stable

### ISSUE THREAD

**Issue by Loyth** [wouterverweirder/kinect2#37]
Hi everyone, I would like to detect when the hand is stable. Do you have a solution for that ? Thanks.

**Comment by amejias101** [comment]
I think that you have to define what exactly you mean by stable

**Comment by Loyth** [comment]
By stable, I mean that I want detect when the hand is motionless. When the hand is in movement, I do some things, and I want to detect when the hand is stable for do other things.

**Comment by wouterverweirder** [comment]
You could keep a history of hand coordinates, and calculate the distance the hand has traveled between frames. If it's below a certain threshold, it's suffice to say the hand is stable.
