### ISSUE TITLE
any limitations? open/closed hand info available?

### ISSUE THREAD

**Issue by flyon** [wouterverweirder/kinect2#4]
Hi, after some research this project seems to be the only way to get kinect 2.0 data in the browser, so thank you for your work. Im currently considering buying a kinect v2, though i need to be sure of what i can use it for in the browser. Since no extra info is on the main page of this project (besides the examples which i cannot yet run) I wonder: is all information from the kinect also availabld in js through this lib? Is for example the new feature of open hand/closed hand/two finger pointer available in the data?

**Comment by wouterverweirder** [comment]
right now the x & y coordinates in depth space are available, as well as the hand state info.
More data (other coordinate spaces) is just a matter of finding the time :-)
