### ISSUE TITLE
Matting based on depth images of the Kinect

### ISSUE THREAD

**Issue by cnwander** [wouterverweirder/kinect2#40]
is there has a method like "AccessUnderlyingBuffer" to get the depth of colorpixel? thanks a lot

**Comment by wouterverweirder** [comment]
Could you elaborate what you're trying to achieve? You can get a combination of data (depth, color, ...) with `kinect.openMultiSourceReader({frameTypes: Kinect2.FrameType.rawDepth | Kinect2.FrameType.color})` and listening for multiSourceFrame events?

**Comment by cnwander** [comment]
thanks. 
i'm trying to achieve is body image matting, and change the backgroud, like this:
![image](https://cloud.githubusercontent.com/assets/1005746/18820597/90ce4186-83d1-11e6-9739-07bd5cdf1d31.png)
![image](https://cloud.githubusercontent.com/assets/1005746/18820606/9af88e78-83d1-11e6-8d8b-8cce5ee25339.png)

**Comment by newmovieclip** [comment]
Aha, https://github.com/wouterverweirder/kinect2/tree/master/examples/greenkey-electron is an example doing just that :-)
