### ISSUE TITLE
Uncaught Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by mariovde** [wouterverweirder/kinect2#42]
Hi all,

I've got this error:
ELECTRON_ASAR.js:173 Uncaught Error: %1 is not a valid Win32 application.
\\?\C:\Users\ida\Documents\myapp\app\node_modules\edge-atom-shell\build\Release\edge.node

could you point me in the right direction on how to get this fixed?

Regards

Mario

**Comment by wouterverweirder** [comment]
Doesn't look like an issue related to this project, as it's referencing edge-atom-shell - a node module not in the dependency tree of this project. What other dependencies does your project have, apart from kinect2?

**Comment by mariovde** [comment]
Solved it.
I needed to rebuild the plugin as a win32 application instead of win64. 
This fixed it.
