### ISSUE TITLE
Save colorData to File

### ISSUE THREAD

**Issue by mariovde** [wouterverweirder/kinect2#44]
#Hi

This is not so much an issue but:
How would you write colorFrame-data (<Buffer ...>) to an actual file ?

`   
     function takeAPicture(){

     var kinect = new Kinect2();
      if(kinect.open()){
       kinect.on('colorFrame', function(newPixelData){
      kinect.close();

      var d = new Date();
      d = d.getTime();

      var pixelUtil= require('pixel-util');

      var imageData = pixelUtil.createImageData(ORIGINAL_IMAGE_WIDTH, ORIGINAL_IMAGE_HEIGHT);

      imageData.data = newPixelData;

      var buffer = new Buffer(newPixelData.length)

      for(var i=0; i<newPixelData.length; i++){
        buffer[i] = newPixelData[i];
      }
      fs.writeFile("C:\\foto.jpg", buffer, (err) => {
        if (err) throw err;
        console.log('It\'s saved!');
      });

    });
    kinect.openColorReader();
      }
    }
`

regards,

Mario

**Comment by wouterverweirder** [comment]
Well, the pixel buffer you get are raw pixel values (bitmap). You should be able to save that data as a .bmp.

If you need compression, you could take a look at examples/color-feed-browser-lwip/index.js - in that example I'm compressing the bitmap as a jpeg (using lwip), before I'm sending it over a socket connection.

**Comment by mariovde** [comment]
When using this code, it says the file is save, but the bmp-file won't open.
It's 8mb large though...

var kinect = new Kinect2();
  if(kinect.open()){
    kinect.on('colorFrame', function(newPixelData){
      kinect.close();
      console.log(newPixelData);
      fs.writeFile("C:/test.bmp", newPixelData,  "binary",function(err) {
        if(err) {
          console.log(err);
        } else {
          console.log("The file was saved!");
        }
      });

    });
    kinect.openColorReader();
  }

**Comment by ACPrice** [comment]
Hey @mariovde I know this is an old thread, but the `newPixelData` you're using above is only the actual data for the pixel values. To save a bitmap that can be opened, the `.bmp` you save needs to also have additional data _before_ those pixel values. That data constitutes the bitmap file "header". 

Check out how this repo adds headers to the bitmap file:

https://github.com/shaozilee/bmp-js/blob/master/lib/encoder.js

That code won't work out of the box for raw Kinect data, but it's close, and a good example regardless.

**Comment by hzjdandan** [comment]
@mariovde   did you solve the problem?

**Comment by hzjdandan** [comment]
> @hzjdandan yes, like described above by ACPrice.

Is it convenient to provide code?    Thank you very much!
