### ISSUE TITLE
How do I check kinect is open or closed?

### ISSUE THREAD

**Issue by BrstDev123** [wouterverweirder/kinect2#46]
Hello, 
I am getting problem in closing the device sensor, I know it can be done using .close() and open using .open() methods , but I wants to check if it is already open then close the sensor, can anyone help me out?

Thank you!

**Comment by JasperBeuls** [comment]
@BrstDev123 
Hey BrstDev123, I have encountered the same problem. Have you found a fix for the .close() not working?

**Comment by tbiinfotech** [comment]
I don't know about a fix for it, I only call .close() again
will reply if any change.
