### ISSUE TITLE
cool adds 

### ISSUE THREAD

**Issue by lo-th** [wouterverweirder/kinect2#50]
hello this libs is clearly the best for webdevelopper 
is still active ?

what would be really great is added SimpleFaceTracking and HDFaceVertex
i see is possible in java https://github.com/ThomasLengeling/KinectPV2

thank you anyway
a webgl 3d developer

**Comment by wouterverweirder** [comment]
I'm still maintaining the project, which is add fixes when things stop working (eg make sure this library still works when new node versions are released). I'm not developing new features myself at the moment.

If you have a pull request with a new feature, I'll be happy to review & merge.
