### ISSUE TITLE
Electron : The specified procedure could not be found

### ISSUE THREAD

**Issue by caitoulin** [wouterverweirder/kinect2#51]
![0G{2_T6NIZ2%000 2W (CH8](https://user-images.githubusercontent.com/48467359/54732312-1342c580-4bce-11e9-9287-a7d360ede7ea.png)
I am certain the file exists, and here is the output of the build script

**Comment by wouterverweirder** [comment]
It looks like an issue with an electron dependency, not with this library. Could you give me more information about:

- the contents of your package.json
- the steps you did (terminal commands) that led to this error?
