### ISSUE TITLE
Usage with Webpack

### ISSUE THREAD

**Issue by AleskiWeb** [wouterverweirder/kinect2#52]
Im trying to use this fantastic package in my application. However when I get through to the library (inside `lib/kinect2.js`) then webpack complains that the module `kinect2.node` cant be found inside the build folder.

![image](https://user-images.githubusercontent.com/8318899/56033839-54d21680-5d1d-11e9-9e6b-bc54d629ce24.png)

Any ideas?

**Comment by AleskiWeb** [comment]
It is something to do with the use of `__direname` in the lib.js file and webpack shimming this to the project root. Any ideas how this could be re-wrote without the use of `__dirname` at the top of the file?

**Comment by wouterverweirder** [comment]
Just did a complete rewrite, issue should no longer be present now.
