### ISSUE TITLE
Usage with electron-builder

### ISSUE THREAD

**Issue by fvonellerts** [wouterverweirder/kinect2#54]
Hi there

This is not a real bug report, as it's likely not this library's fault - but it would be a good addition to the readme file.
When using this library with an `electron-builder` project, the (additional) rebuild triggered by `electron-builder` messes up the `kinect2` build. This can be circumvented by using the builder configuration `npmRebuild: false`.

Best regards,
Fabian

**Comment by wouterverweirder** [comment]
Just released version 0.2.0 of this library, which is a complete rewrite on the native C side, making it compatible with modern node versions. Additional benefit is that no rebuilds are needed to use it in electron apps.
