### ISSUE TITLE
Support for new version of Kinect

### ISSUE THREAD

**Issue by shreyapandit** [wouterverweirder/kinect2#55]
Hi there,

Thanks for the great work on your package 🥇 

Microsoft recently announced the new Kinect sensor:
https://azure.microsoft.com/en-us/services/kinect-dk/

Would this package work with the new sensor as well?

Thanks!

**Comment by wouterverweirder** [comment]
Hey - Would love to, trying to get my hands on a sensor as it's not available yet in Europe...

**Comment by shreyapandit** [comment]
Thanks for your response! I am based out of US and will get a sensor next week. Would love to constribute if you could help me get started on what would be first steps in that regard. Cheers!

**Comment by wouterverweirder** [comment]
Got my Azure Kinect last week and started work on an extension: https://github.com/wouterverweirder/kinect-azure
