### ISSUE TITLE
Which example corresponds to the image in the README?

### ISSUE THREAD

**Issue by shreyapandit** [wouterverweirder/kinect2#56]
Hi, I am also trying to ovrerlay color + skeletal data as shown in the image on the README.

Could you point me to an example that covers how to achieve that?

Thanks a ton

**Comment by wouterverweirder** [comment]
You can check out https://github.com/wouterverweirder/kinect2/blob/master/examples/electron/renderer/demos/multi-source-reader.html for this functionality.
