### ISSUE TITLE
Starting and stopping cameras crashes my code

### ISSUE THREAD

**Issue by Chrisbright10** [wouterverweirder/kinect2#59]
Similar to the issue linked below, this codebase is subject to the same issue. I am getting "ThreadSafeFunction::operator = You cannot assign a new TSFN because existing one is still alive." I would love it if we could implement the same fix here... Thanks for your hard work in updating this repo!!

https://github.com/wouterverweirder/kinect-azure/issues/6

**Comment by wouterverweirder** [comment]
Ah, thanks for catching that one. Unfortunately, I don't have access to my windows machine right now, as I've lent it to a colleague of mine who had computer problems. So, it'll have to wait until I have my machine back 😅

**Comment by Chrisbright10** [comment]
No worries, but thank you for being so willing to update it! You're a champ!

**Comment by wouterverweirder** [comment]
Just released v0.2.1 - which fixes this issue.
You can now await the close functions or pass in a callback, as illustrated in the demo below. It works for all close functions and for the generic kinect.close function as well:

https://github.com/wouterverweirder/kinect2/blob/1879a00d9bc0a81458b39e4d5f2f0712f84615a0/examples/node/restart-multiple-times-color.js#L1-L33
