### ISSUE TITLE
Adding infrared to multiSourceFrame

### ISSUE THREAD

**Issue by lisajamhoury** [wouterverweirder/kinect2#67]
Hello! I was wondering if you plan to implement infrared in multiSourceFrame. It looks like it is marked as a possible todo in the source code. I've had a request for it in Kinectron, so thought I'd check in about it. 

Thanks!

**Comment by wouterverweirder** [comment]
Hi Lisa,

Released v0.2.6 which adds infrared and long exposure infrared to the multi source frames: https://github.com/wouterverweirder/kinect2/releases/tag/v0.2.6

Basic example at https://github.com/wouterverweirder/kinect2/blob/master/examples/electron/renderer/demos/multi-source-reader-infrared.html

**Comment by lisajamhoury** [comment]
Excellent. Thank you!
