### ISSUE TITLE
Issues with latest node.js v.0.12.2

### ISSUE THREAD

**Issue by multimedial** [wouterverweirder/kinect2#7]
Hello, 

I am trying to get your kinect2 modul up and running for a pet project I am working on, yet I get errors when using it with the current node.js version 0.12.2 - the error lies in the edge bridge module not having been compiled for the current node version apparently (see below):

Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.
C:\Users\chris>npm install C:\Users\chris\Desktop\kinect2-master\kinect2-master

    edge@0.9.3 install C:\Users\chris\node_modules\kinect2\node_modules\edge

    node tools/install.js

***************************************

[Error: The edge module has not been pre-compiled for node.js version v0.12.2. Y

ou must build a custom version of edge.node. Please refer to https://github.com/

tjanczuk/edge for building instructions.]

***************************************

Success: platform check for edge.js: node.js ia32 v0.12.2

kinect2@0.0.8 node_modules\kinect2

└── edge@0.9.3 (edge-cs@0.2.7)

**Comment by cecilemuller** [comment]
The latest Edge works with the current Node 0.12.4  (but [not io.js](https://github.com/tjanczuk/edge/issues/235) unfortunately  ), so until the version number is updated in kinect2's package.json, you can get it working this way:

	npm install kinect2 --save
	cd node_modules/kinect2
	npm uninstall edge --save
	npm install edge --save
